[project]
name = "dl-optimizers-experiments"
version = "0.1.0"
requires-python = ">=3.11"
authors = [{ name = "irinszn" }]
dependencies = [
    "torch",
    "torchvision",
    "torch-optimizer",
    "mlflow",
    "optuna",
    "pandas",
    "scipy",
    "scikit-learn",
    "tabulate",
    "tqdm",
    "pyyaml",
    "pillow",
    "numpy",
    "seedbank",
    "pyngrok",
]

[project.urls]
repository = "https://github.com/irinszn/DL_Optimizers_Experiments.git"

[dependency-groups]
dev = [
    "black==23.11.0",
    "mypy==1.14.1",
    "pytest==8.3.4",
    "isort==5.12.0",
    "hypothesis==6.115.6",
    "types-pyyaml>=6.0.12.20260408",
    "types-tabulate>=0.10.0.20260408",
]

[tool.isort]
profile = "black"
line_length = 120

[tool.black]
line-length = 120

[tool.mypy]
files = ["src"]
install_types = "True"
non_interactive = "True"
disallow_untyped_defs = "True"
ignore_missing_imports = "True"
show_error_codes = "True"
warn_redundant_casts = "True"
warn_unused_configs = "True"
warn_unused_ignores = "True"
allow_redefinition = "True"
warn_no_return = "False"
no_implicit_optional = "False"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["--color=yes", "-s"]