name: Main

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: "installation"
        run: uv sync --dev
      - name: "black"
        run: uv run black . --check --diff --color
      - name: "isort"
        run: uv run isort . --check --diff
      - name: "mypy"
        run: uv run mypy
      - name: "pytests"
        run: uv run pytest